// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0Eu5iuIh6fqTjiw8wuwtdpr6Bx7wU4w',
    appId: '1:712813591697:web:4a578f74df33133c485330',
    messagingSenderId: '712813591697',
    projectId: 'targetku-001',
    authDomain: 'targetku-001.firebaseapp.com',
    storageBucket: 'targetku-001.firebasestorage.app',
    measurementId: 'G-8Q9H0VNPE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTf89b-Q__aHhLeV0R6acwx39jv_3yNo',
    appId: '1:712813591697:android:bf3364c27ae8174c485330',
    messagingSenderId: '712813591697',
    projectId: 'targetku-001',
    storageBucket: 'targetku-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgptECSDZO9P8JSVEZN4lM4mK45QGqdI',
    appId: '1:712813591697:ios:e14bdb7348f9cef0485330',
    messagingSenderId: '712813591697',
    projectId: 'targetku-001',
    storageBucket: 'targetku-001.firebasestorage.app',
    iosBundleId: 'com.example.targetku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgptECSDZO9P8JSVEZN4lM4mK45QGqdI',
    appId: '1:712813591697:ios:e14bdb7348f9cef0485330',
    messagingSenderId: '712813591697',
    projectId: 'targetku-001',
    storageBucket: 'targetku-001.firebasestorage.app',
    iosBundleId: 'com.example.targetku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK0Eu5iuIh6fqTjiw8wuwtdpr6Bx7wU4w',
    appId: '1:712813591697:web:ee3016b3ad054b4e485330',
    messagingSenderId: '712813591697',
    projectId: 'targetku-001',
    authDomain: 'targetku-001.firebaseapp.com',
    storageBucket: 'targetku-001.firebasestorage.app',
    measurementId: 'G-NXEGE1X7C1',
  );

}